# NumPy Introduction

In [1]:
import numpy as np
import time

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# Checking Python list vs NumPy array in execution time
size = 100000000
li = list(range(size))
start = time.time() # It gives the current time in seconds
square = [x**2 for x in li]
end = time.time() 
print(f"Using Python list: {end - start} seconds")

# For numPy array
array = np.array(li)
start_time = time.time()
sqr = array ** 2
end_time = time.time()
print(f"Using NumPy array: {end_time - start_time} seconds")


Using Python list: 17.05262780189514 seconds
Using NumPy array: 0.16810035705566406 seconds


In [7]:
# memory usage in terms of bytes 
import sys
print(f"Memory usage of python list: {sys.getsizeof(li)} bytes")
# print(f"Memory usage of numPy array: {sys.getsizeof(array)} bytes")
# or
print(f"Memory usage of numPy array: {array.nbytes} bytes")

Memory usage of python list: 800000056 bytes
Memory usage of numPy array: 400000000 bytes


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1, type(arr1), arr1.dtype, arr.shape)

arr2 = np.array([1, 2, 3, 3, 5, 6, "Prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape) #dtype is for data type of the array.

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
print(arr2D, type(arr2D), arr2D.dtype, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int32 (5,)
['1' '2' '3' '3' '5' '6' 'Prime'] <class 'numpy.ndarray'> <U11 (7,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int32 (3, 3)


In [15]:
# Creating numPy arrays using built-in functions
arr = np.zeros((2,3), dtype=int) # Prefill with zeros
print(arr, arr.shape)

arr1 = np.ones((2,3), dtype=int)
print(arr1, arr1.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
