# NumPy Introduction

In [2]:
import numpy as np
import time

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
# Checking Python list vs NumPy array in execution time
size = 100000000
li = list(range(size))
start = time.time() # It gives the current time in seconds
square = [x**2 for x in li]
end = time.time() 
print(f"Using Python list: {end - start} seconds")

# For numPy array
array = np.array(li)
start_time = time.time()
sqr = array ** 2
end_time = time.time()
print(f"Using NumPy array: {end_time - start_time} seconds")


Using Python list: 25.331223964691162 seconds
Using NumPy array: 0.26575350761413574 seconds


In [5]:
# memory usage in terms of bytes 
import sys
print(f"Memory usage of python list: {sys.getsizeof(li)} bytes")
# print(f"Memory usage of numPy array: {sys.getsizeof(array)} bytes")
# or
print(f"Memory usage of numPy array: {array.nbytes} bytes")

Memory usage of python list: 800000056 bytes
Memory usage of numPy array: 400000000 bytes


In [6]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1, type(arr1), arr1.dtype, arr.shape)

arr2 = np.array([1, 2, 3, 3, 5, 6, "Prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape) #dtype is for data type of the array.

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
print(arr2D, type(arr2D), arr2D.dtype, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int32 (5,)
['1' '2' '3' '3' '5' '6' 'Prime'] <class 'numpy.ndarray'> <U11 (7,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int32 (3, 3)


In [7]:
# Creating numPy arrays using built-in functions
# 1: 
arr = np.zeros((2,3), dtype=int) # Prefill with zeros
print(arr, arr.shape)

# 2: 
arr1 = np.ones((2,3), dtype=int) # Prefill with ones
print(arr1, arr1.shape)

# 3: 
arr2 = np.full((3,4), 10, dtype=int) # full fuction to create an array with specific value
print(arr2, arr2.shape)

# 4: 
arr3 = np.eye((3), dtype=int) # eye function is used for creating identity matrix
print(arr3, arr3.shape)

# 5:
arr4 = np.arange(1, 11) # arange elements from 1 to 10
print(arr4, arr4.shape)

eg  = np.arange(0, 11, 2)
print(eg, eg.shape)

# 6: 
arr5 = np.linspace(1, 100, 4) # linspace to create evenly spaced arrays
print(arr5, arr5.shape)


[[0 0 0]
 [0 0 0]]

 (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]] (3, 4)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[ 1  2  3  4  5  6  7  8  9 10] (10,)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [8]:
# Properties of numPy arrays
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr)
print(arr.shape) # For shape of the array
print(arr.size) # For total number of elements in the array
print(arr.dtype) # For data type of the array
print(arr.ndim) # For number of dimensions in the array

# Doing type casting in numPy arrays
# int to float
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
int32
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [9]:
# Operations on numPy arrays

# Reshaping
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

# Now reshaping it into 3*2
reshape_arr = arr.reshape(3,2)
print(reshape_arr, reshape_arr.shape)

# Can flattent the array as well, means to convert it into 1D array
flatten_arr = arr.flatten()
print(flatten_arr, flatten_arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [ ]:
# Indexing on numPy arrays
arr = np.array([1, 2, 3, 4, 5]) # 1D array
print(arr[0]) # 1
print(arr[4]) # 5

1
5


In [ ]:
# using 2D array
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2D[0, 0]) # 1
print(arr2D[0, 2]) # 3

print(arr2D[1, 0]) # 4
print(arr2D[1, 2]) # 6

print(arr2D[2, 0]) # 7
print(arr2D[2, 2]) # 9

# Fancy indexing 
arr = np.array([10, 20, 30, 40, 50])
# Using fancy indexing to access specific elements
idx = [0, 2, 4]
print(arr[idx]) # 10 30 50 

#using in 2D array
index = [0, 2]
print(arr2D[index]) # [[1, 2, 3], [7, 8, 9]]

# Boolean Indexing
print(arr[arr> 20]) # 30 40 50
print(arr[arr % 2 == 0]) # 10 20 30 40 50



1
3
4
6
7
9
[10 30 50]
[[1 2 3]
 [7 8 9]]
[30 40 50]
[10 20 30 40 50]
