# NumPy Introduction

In [1]:
import numpy as np
import time

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# Checking Python list vs NumPy array in execution time
size = 100000000
li = list(range(size))
start = time.time() # It gives the current time in seconds
square = [x**2 for x in li]
end = time.time() 
print(f"Using Python list: {end - start} seconds")

# For numPy array
array = np.array(li)
start_time = time.time()
sqr = array ** 2
end_time = time.time()
print(f"Using NumPy array: {end_time - start_time} seconds")


Using Python list: 25.372833251953125 seconds
Using NumPy array: 0.4429025650024414 seconds


In [4]:
# memory usage in terms of bytes 
import sys
print(f"Memory usage of python list: {sys.getsizeof(li)} bytes")
# print(f"Memory usage of numPy array: {sys.getsizeof(array)} bytes")
# or
print(f"Memory usage of numPy array: {array.nbytes} bytes")

Memory usage of python list: 800000056 bytes
Memory usage of numPy array: 400000000 bytes


In [5]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1, type(arr1), arr1.dtype, arr.shape)

arr2 = np.array([1, 2, 3, 3, 5, 6, "Prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape) #dtype is for data type of the array.

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
print(arr2D, type(arr2D), arr2D.dtype, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int32 (5,)
['1' '2' '3' '3' '5' '6' 'Prime'] <class 'numpy.ndarray'> <U11 (7,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int32 (3, 3)


In [6]:
# Creating numPy arrays using built-in functions
# 1: 
arr = np.zeros((2,3), dtype=int) # Prefill with zeros
print(arr, arr.shape)

# 2: 
arr1 = np.ones((2,3), dtype=int) # Prefill with ones
print(arr1, arr1.shape)

# 3: 
arr2 = np.full((3,4), 10, dtype=int) # full fuction to create an array with specific value
print(arr2, arr2.shape)

# 4: 
arr3 = np.eye((3), dtype=int) # eye function is used for creating identity matrix
print(arr3, arr3.shape)

# 5:
arr4 = np.arange(1, 11) # arange elements from 1 to 10
print(arr4, arr4.shape)

eg  = np.arange(0, 11, 2)
print(eg, eg.shape)

# 6: 
arr5 = np.linspace(1, 100, 4) # linspace to create evenly spaced arrays
print(arr5, arr5.shape)


[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]] (3, 4)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[ 1  2  3  4  5  6  7  8  9 10] (10,)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [7]:
# Properties of numPy arrays
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr)
print(arr.shape) # For shape of the array
print(arr.size) # For total number of elements in the array
print(arr.dtype) # For data type of the array
print(arr.ndim) # For number of dimensions in the array

# Doing type casting in numPy arrays
# int to float
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
int32
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [8]:
# Operations on numPy arrays

# Reshaping
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

# Now reshaping it into 3*2
reshape_arr = arr.reshape(3,2)
print(reshape_arr, reshape_arr.shape)

# Can flattent the array as well, means to convert it into 1D array
flatten_arr = arr.flatten()
print(flatten_arr, flatten_arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [9]:
# Indexing on numPy arrays
arr = np.array([1, 2, 3, 4, 5]) # 1D array
print(arr[0]) # 1
print(arr[4]) # 5

1
5


In [10]:
# using 2D array
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2D[0, 0]) # 1
print(arr2D[0, 2]) # 3

print(arr2D[1, 0]) # 4
print(arr2D[1, 2]) # 6

print(arr2D[2, 0]) # 7
print(arr2D[2, 2]) # 9

# Fancy indexing 
arr = np.array([10, 20, 30, 40, 50])
# Using fancy indexing to access specific elements
idx = [0, 2, 4]
print(arr[idx]) # 10 30 50 

#using in 2D array
index = [0, 2]
print(arr2D[index]) # [[1, 2, 3], [7, 8, 9]]

# Boolean Indexing
print(arr[arr> 20]) # 30 40 50
print(arr[arr % 2 == 0]) # 10 20 30 40 50

1
3
4
6
7
9
[10 30 50]
[[1 2 3]
 [7 8 9]]
[30 40 50]
[10 20 30 40 50]


In [11]:
# Slicing on numPy arrays
# [start, end, step]
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[0:5])
print(arr[0:])
print(arr[:7])
print(arr[::2]) # skip every 2nd element

[1 2 3 4 5]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[1 3 5 7]


In [12]:
# Copy vs View in numPy arrays
nums = [1, 2, 3, 4, 5, 6]
sub_nums = nums[1:4] # 2 3 4
print(sub_nums)
sub_nums[1] = 20

print(sub_nums)
print(nums)

print("Using numPy array")
arr = np.array([1, 2, 3, 4, 5])
# sub_arr = arr[1:4].copy() # 2 3 4, if used copy then it will not change the original array, copying the view not original array
sub_arr = arr[1:4] # 2 3 4
print(sub_arr)
sub_arr[1] = 10
print(sub_arr)
print(arr)


[2, 3, 4]
[2, 20, 4]
[1, 2, 3, 4, 5, 6]
Using numPy array
[2 3 4]
[ 2 10  4]
[ 1  2 10  4  5]


In [13]:
# Data Types in numPy arrays
arr = np.array([1, 2, 3, 4, 5])
print(arr, arr.dtype) # int32

arr2 = np.array([10, 20, 30.5, 40, 50])
print(arr2, arr2.dtype) # float64

sr_arr = np.array(["data", "science", 1, 2])
print(sr_arr, sr_arr.dtype) # U11

# Creating complex numbers
com_arr = np.array([5 + 8j, 2+ 3j])
print(com_arr, com_arr.dtype) # complex128

com_arr1 = np.array([7 + 5j])
com_arr2 = np.array([3 + 7j])
print(com_arr1 + com_arr2, com_arr1 - com_arr2)

# Note: Not advised to use numPy arrays to store strings data and object data as they convert whole array into string data and object data type respectively.
# Just for example: 
obj_arr = np.array(["data", {1, 2, 3}, 10.2])
print(obj_arr, obj_arr.dtype) # object

[1 2 3 4 5] int32
[10.  20.  30.5 40.  50. ] float64
['data' 'science' '1' '2'] <U11
[5.+8.j 2.+3.j] complex128
[10.+12.j] [4.-2.j]
['data' {1, 2, 3} 10.2] object


In [14]:
# Multi-dimensional arrays in numPy
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)

print("Sum of arr2D:", arr2D.sum())

# We can perform sum operation row/column wise too
# For row
print("Sum of arr2D row wise", arr2D.sum(axis=1)) # axis=1 means row wise sum

# For column
print("Sum of arr2D column wise", arr2D.sum(axis=0)) # axis=0 means column wise sum

# We can perform slicing axis wise too
print("Slicing", arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of arr2D: 45
Sum of arr2D row wise [ 6 15 24]
Sum of arr2D column wise [12 15 18]
Slicing [[2]
 [5]]


In [31]:
# Creating a 3D array of size 2*3*2
# 2 layers, 3 rows and 2 columns
arr3D = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])
print(arr3D)
print("Shape of array: ", arr3D.shape)

#Indexing
# let's acces 4 from array3D
print("Index of four:",  arr3D[0, 1, 1])

# Accessing 9 
print("For 9 in array:", arr3D[1, 1, 0])

# Accessing 8
print("For eight in array:", arr3D[1, 0, 1])
print("------------------------------------------")

# Using slicing
print("Using Slicing")
print("For first row", arr3D[:, 0, :]) # First row from all layers
print("For second row", arr3D[:, 1, :]) # Second row from all layers
print("For third row", arr3D[:, 2, :]) # Third row from all layers

print("For first column", arr3D[:, :, 0]) # First column from all layers
print("For second column", arr3D[:, :, 1]) # Second column from all layers 

print("------------------------------------------")
arr3D[:, 0, :] = 99
print(arr3D)




[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Shape of array:  (2, 3, 2)
Index of four: 4
For 9 in array: 9
For eight in array: 8
------------------------------------------
Using Slicing
For first row [[1 2]
 [7 8]]
For second row [[ 3  4]
 [ 9 10]]
For third row [[ 5  6]
 [11 12]]
For first column [[ 1  3  5]
 [ 7  9 11]]
For second column [[ 2  4  6]
 [ 8 10 12]]
------------------------------------------
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [ ]:
# Broadcasting in numPy arrays
# It means scaling our arrays without using extra memory.

# Normalization of an array

norm_arr = np.array([[10, 20], [30, 40]])
mean = norm_arr.mean()
std = norm_arr.std()

print("Mean:", mean)
print("Standard Deviation:", std)

normalized_arr = (norm_arr - mean) / std
print("Normalized array: ", normalized_arr)
# Mean would turn into 0 and Standard Deviation would be 1

Mean: 25.0
Standard Deviation: 11.180339887498949
Normalized array:  [[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
